### PR TITLE
fix: Changed the size and color on the modal

### PR DESCRIPTION
**Pull request by anaritadauane**
- Changed the colors of the modal and the input text and field sizes 

Screenshot 2024-06-16 at 00 31 03

### CODE REVIEW

**Comment by anaritadauane** [comment]
LMK if you would like to have a dark color theme.

**Comment by gitgoap** [comment]
@anaritadauane 
Paste a picture of a new coloured extension.
It will be easy for me to review.

**Comment by anaritadauane** [comment]
I attached the picture, please check

**Comment by gitgoap** [comment]
@anaritadauane Good work!!

**Review by gitgoap — APPROVED** [review]

**Comment by gitgoap** [comment]
Closes issue #50

**Comment by anaritadauane** [comment]
> @anaritadauane Good work!!

Thank you!
Willing to contribute more 🙂

**Pull request merged**
