### PR TITLE
Update Code Sample image in the README.md

### PR DESCRIPTION
**Pull request by meetalik8**
Fixed Issue Assigned : #52

### CODE REVIEW

**Comment by gitgoap** [comment]
@meetalik8 
Can you crop the image better from the bottom.

**Comment by meetalik8** [comment]
@gitgoap hello do you want me to crop the terminal?

**Comment by gitgoap** [comment]
@meetalik8 No at bottom a thin line of windows bar is seen, just remove that.

I only want the tutorial portion to be present in the image.

**Comment by meetalik8** [comment]
image
This is what it looks now

**Review by gitgoap — APPROVED** [review]

**Pull request merged**
