### PR TITLE
Save Api key issue no #51

### PR DESCRIPTION
**Pull request by vishalmaurya850**
Now you will be able to save api using the code

### CODE REVIEW

**Review by vishalmaurya850 — COMMENTED** [review]
You can add this code in your app for saving api key

**Comment by gitgoap** [comment]
@It's not saving the API keys
- You should put a button on the extension that gives users the option if they want to save the API key or not.
- The next time the user uses the extension then the API key appears already filled in the API space bar.

**Comment by gitgoap** [comment]
@vishalmaurya850 

Test it robustly if you are unable to make this feature then inform me.
I'll assign this issue to someone else.

**Comment by gitgoap** [comment]
> You cannot save an api key for anyone else you will have to give your api key which helps them to directly address the snapshot without extra effort for getting ready with your project. @gitgoap Please Reply
>  And if you want to save that api key for someone you will have to get an storage area which is provided by Gemini for Endpoint Api I'd for that you will have to provide your own endpoint url from gemini

You should research about API cost of Gemini.
If I provide my API key then I have to bear the cost of everyone who uses this tool.

Also there are several ways to store API key in browser, no need of storage device.

**Comment by gitgoap** [comment]
@vishalmaurya850 
Are you working on this issue or should I assign it to someone else?

**Comment by vishalmaurya850** [comment]
Wait for 1 hour, as I am working on it.

**Pull request closed without merging**
