### PR TITLE
Save API Key

### PR DESCRIPTION
**Pull request by vishalmaurya850**
#51 Issue Please run the code and merge it.

### CODE REVIEW

**Review by vishalmaurya850 — COMMENTED** [review]
It's correct from my side

**Comment by gitgoap** [comment]
@vishalmaurya850 
It's still not saving the API key in the API key space.

If it's working on your machine then  upload a demo working video.

**Comment by vishalmaurya850** [comment]
I want to talk

**Comment by vishalmaurya850** [comment]
Now you can Check it's saving the api key

**Review by vishalmaurya850 — COMMENTED** [review]
Now it's done

**Comment by gitgoap** [comment]
@vishalmaurya850 
Can you share a demo (like screen record your PC) of your feature before I test it out in my system

**Comment by vishalmaurya850** [comment]
I am not with my laptop if you are able to check please check it

**Comment by vishalmaurya850** [comment]
Where to send the video?

**Comment by vishalmaurya850** [comment]
Uploading Screen Recording 2024-06-26 220218.mp4…

**Comment by vishalmaurya850** [comment]
https://github.com/gitgoap/AI-Snipping-Tool/assets/40622097/4e755723-940a-4a07-995e-9b7757a5f6f2

**Comment by gitgoap** [comment]
@vishalmaurya850 
You have made a completely different popup than the original.
How are we going to take screenshot from this?

**Comment by vishalmaurya850** [comment]
If you tell me where is the save api variable in your app then I will connect it with that so that the user will only have to save api once and can take screenshot anytime

**Comment by vishalmaurya850** [comment]
Not the Saving API variable but there is a BOX for API in which the user Inputs the value and click on get answer so provide me the variable so that I can !erge it..
Thank You

**Comment by vishalmaurya850** [comment]
Please Reply

**Comment by gitgoap** [comment]
@vishalmaurya850 
Check https://github.com/gitgoap/AI-Snipping-Tool/pull/49/files
line 720- 760

**Comment by gitgoap** [comment]
Solved #77

**Pull request closed without merging**
